// SPDX-License-Identifier: Apache-2.0
import {
  readFile,
  mkdir,
  rename,
  writeFile,
  readdir,
  unlink,
} from "node:fs/promises";
import { resolve, dirname, join } from "node:path";
import { spawnSync } from "node:child_process";
import { compile } from "./parser.js";
import { emitGo, scopeHelper, sourceHash } from "./emit.js";
import type { Measurements } from "./emit.js";

interface Entry {
  name: string;
  source: string;
  export?: string;
  output: string;
  measurements?: string;
  profile?: { state: string; width: number; height: number; scale: number };
}
interface Config {
  schema: 1;
  package: string;
  entries: Entry[];
}
interface Options {
  config: string;
  entry?: string;
  measurements?: string;
  check: boolean;
  analyze?: boolean;
}

export async function generate(options: Options): Promise<void> {
  const configPath = resolve(options.config);
  const root = dirname(configPath);
  const config = JSON.parse(await readFile(configPath, "utf8")) as Config;
  if (
    config.schema !== 1 ||
    !Array.isArray(config.entries) ||
    !config.entries.length
  )
    throw new Error("Configuración schema:1 con entries obligatoria.");
  const entries = options.entry
    ? config.entries.filter((entry) => entry.name === options.entry)
    : config.entries;
  if (!entries.length) throw new Error(`Entrada desconocida: ${options.entry}`);
  if (options.measurements && entries.length !== 1)
    throw new Error(
      "--measurements requiere --entry para asociar una captura a una sola página.",
    );
  if (
    new Set(config.entries.map((entry) => entry.name)).size !==
    config.entries.length
  )
    throw new Error("Nombres de entrada duplicados en un paquete Go.");
  const outputs = new Map<string, string>();
  const reports: { path: string; text: string }[] = [];
  for (const entry of entries) {
    const program = await compile(resolve(root, entry.source), entry.export, {
      root,
    });
    if (options.analyze) {
      process.stdout.write(
        JSON.stringify(
          { name: entry.name, sourceHash: sourceHash(program), program },
          null,
          2,
        ) + "\n",
      );
      continue;
    }
    const measurementPath = options.measurements ?? entry.measurements;
    const measurements = measurementPath
      ? (JSON.parse(
          await readFile(resolve(root, measurementPath), "utf8"),
        ) as Measurements)
      : undefined;
    const output = resolve(root, entry.output);
    if (!output.endsWith(".go"))
      throw new Error(`${output}: la salida debe terminar en .go.`);
    if (outputs.has(output)) throw new Error(`Salida duplicada: ${output}`);
    const code = emitGo(program, {
      name: entry.name,
      packageName: config.package,
      ...(entry.profile ? { profile: entry.profile } : {}),
      ...(measurements ? { measurements } : {}),
    });
    const formatted = spawnSync("gofmt", [], { input: code, encoding: "utf8" });
    if (formatted.error)
      throw new Error(
        "gofmt es necesario para generar código Go. Instala Go en el entorno de generación.",
      );
    if (formatted.status !== 0)
      throw new Error(`Código Go inválido: ${formatted.stderr}`);
    outputs.set(output, formatted.stdout);
    const report = {
      schema: 1,
      name: entry.name,
      sourceHash: sourceHash(program),
      sources: program.sources,
      actions: program.actions,
      components: program.components.map((component) => component.name),
      compatibility: "declarative-stage-1",
      visual: {
        measured: Boolean(measurements),
        pixelPerfectVerified: false,
        ...(measurements
          ? { state: measurements.state, viewport: measurements.viewport }
          : {}),
      },
    };
    reports.push({
      path: output.replace(/\.go$/, ".report.json"),
      text: JSON.stringify(report, null, 2) + "\n",
    });
  }
  if (options.analyze) return;
  const directories = new Set([...outputs.keys()].map(dirname));
  for (const directory of directories) {
    const formatted = spawnSync("gofmt", [], {
      input: `// Code generated by astro-fyne. DO NOT EDIT.\n// SPDX-License-Identifier: Apache-2.0\npackage ${config.package}\nimport webui "github.com/thinkddr/astro-fyne/native"\n${scopeHelper}`,
      encoding: "utf8",
    });
    if (formatted.status !== 0)
      throw new Error(`Helper Go inválido: ${formatted.stderr}`);
    outputs.set(join(directory, "astro_fyne_scope.gen.go"), formatted.stdout);
  }
  // Parse and format every entry before any write; unsupported source leaves existing output intact.
  const artifacts = [...outputs]
    .map(([path, text]) => ({ path, text }))
    .concat(reports);
  if (options.check) {
    for (const artifact of artifacts) {
      const saved = await readFile(artifact.path, "utf8").catch(() => "");
      if (saved !== artifact.text)
        throw new Error(`Generado desactualizado: ${artifact.path}`);
    }
  } else {
    for (const artifact of artifacts) {
      await mkdir(dirname(artifact.path), { recursive: true });
      const temporary = `${artifact.path}.${process.pid}.tmp`;
      try {
        await writeFile(temporary, artifact.text);
        await rename(temporary, artifact.path);
      } finally {
        await unlink(temporary).catch(() => undefined);
      }
    }
  }
  process.stdout.write(
    `${options.check ? "Comprobadas" : "Generadas"} ${entries.length} entradas; fidelidad visual requiere comparación de capturas.\n`,
  );
}

async function treeFingerprint(root: string): Promise<string> {
  const paths: string[] = [];
  async function scan(directory: string): Promise<void> {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      if (["node_modules", ".git", "dist", ".astro"].includes(entry.name))
        continue;
      const path = join(directory, entry.name);
      if (entry.isDirectory()) await scan(path);
      else if (
        /\.(astro|tsx|ts|css|json)$/.test(entry.name) &&
        !entry.name.endsWith(".report.json")
      )
        paths.push(path);
    }
  }
  await scan(root);
  const { createHash } = await import("node:crypto");
  const hash = createHash("sha256");
  for (const path of paths.sort()) {
    hash.update(path);
    hash.update(await readFile(path));
  }
  return hash.digest("hex");
}

async function main(): Promise<void> {
  const argv = process.argv.slice(2);
  const command = argv.shift();
  if (!["generate", "check", "watch", "analyze"].includes(command ?? ""))
    throw new Error(
      "Uso: astro-fyne generate|check|watch|analyze --config archivo.json [--entry Nombre] [--measurements archivo.json]",
    );
  const options: Options = {
    config: "astro-fyne.json",
    check: command === "check",
    analyze: command === "analyze",
  };
  while (argv.length) {
    const flag = argv.shift();
    const value = argv.shift();
    if (!value) throw new Error(`Falta valor de ${flag}`);
    if (flag === "--config") options.config = value;
    else if (flag === "--entry") options.entry = value;
    else if (flag === "--measurements") options.measurements = value;
    else throw new Error(`Opción desconocida: ${flag}`);
  }
  await generate(options);
  if (command !== "watch") return;
  const root = dirname(resolve(options.config));
  let previous = await treeFingerprint(root);
  // Recursive fs.watch differs between OSes. Content hashes also catch atomic saves.
  for (;;) {
    await new Promise((done) => setTimeout(done, 500));
    const current = await treeFingerprint(root);
    if (current === previous) continue;
    previous = current;
    try {
      await generate({ ...options, check: false });
    } catch (error) {
      process.stderr.write(
        `${error instanceof Error ? error.message : error}\n`,
      );
    }
  }
}

if (import.meta.main)
  main().catch((error: unknown) => {
    process.stderr.write(
      `${error instanceof Error ? error.message : String(error)}\n`,
    );
    process.exitCode = 1;
  });
