// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Astro Fyne contributors.

import { readFile } from "node:fs/promises";
import { resolve, join, dirname } from "node:path";
import { spawnSync } from "node:child_process";
import {
  applyArtifacts,
  generatedJSON,
  generatedText,
  type Artifact,
} from "./artifacts.ts";
import { readCLIJSON, usageError } from "./cli-help.ts";
import { bundleJavascript, validateJavascriptArchive } from "./javascript.ts";
import type { JavascriptArchive } from "./javascript-types.ts";

interface Options {
  source?: string;
  program?: string;
  out: string;
  name: string;
  direction: "native" | "web";
  selected?: string;
  props?: string;
  actions?: string[];
  actionsModule?: string;
  packageName?: string;
  check?: boolean;
}
const header =
  "// Code generated by astro-fyne. DO NOT EDIT.\n// SPDX-License-Identifier: Apache-2.0\n";
const literal = (value: unknown) =>
  JSON.stringify(value)
    .replaceAll("\u2028", "\\u2028")
    .replaceAll("\u2029", "\\u2029");

export async function generateJavascript(options: Options) {
  if (
    !/^[A-Z][A-Za-z0-9_]*$/.test(options.name) ||
    !/^[A-Za-z][A-Za-z0-9_]*$/.test(options.packageName ?? "generated")
  )
    throw new Error("JavaScript widget name/package must be Go identifiers");
  if (!!options.source === !!options.program)
    throw new Error(
      "JavaScript mode requires exactly one --source or --program",
    );
  if (options.program && (options.props || options.selected || options.actions))
    throw new Error("Program input already declares props, export and actions");
  const archive = options.program
    ? await validateJavascriptArchive(
        await readCLIJSON(resolve(options.program), "JavaScript program"),
      )
    : await bundleJavascript(
        options.source!,
        options.selected,
        options.props
          ? ((await readCLIJSON(
              resolve(options.props),
              "JavaScript props",
            )) as Record<string, unknown>)
          : {},
        options.actions ?? [],
      );
  const output = resolve(options.out),
    artifacts: Artifact[] = [];
  const text = (
    path: string,
    content: string,
    marker = header.split("\n")[0]!,
  ) =>
    artifacts.push({
      path: join(output, path),
      root: output,
      content,
      isOwned: generatedText(marker),
    });
  if (options.direction === "native") {
    const code = `${header}package ${options.packageName ?? "generated"}
import("encoding/json";"errors";webui "github.com/thinkddr/astro-fyne/native";jsruntime "github.com/thinkddr/astro-fyne/native/javascript")
const ${options.name}JavascriptArchive = ${literal(JSON.stringify(archive))}
type ${options.name}Widget = jsruntime.Widget
func New${options.name}(props webui.Scope,actions webui.Actions,backends ...webui.Backend)(*${options.name}Widget,error){
var archive jsruntime.Archive;if err:=json.Unmarshal([]byte(${options.name}JavascriptArchive),&archive);err!=nil{return nil,err}
if len(props)>0 {if len(archive.Events)>0||archive.Frame!=nil{return nil,errors.New("javascript: replay requires original props; regenerate source to replace them")};data,err:=json.Marshal(props);if err!=nil{return nil,err};archive.Props=data}
return jsruntime.New(archive,actions,backends...)
}
`;
    const formatted = spawnSync("gofmt", [], {
      input: code,
      encoding: "utf8",
      maxBuffer: 128 * 1024 * 1024,
    });
    if (formatted.error || formatted.status !== 0)
      throw new Error(
        "Cannot format JavaScript widget: " +
          (formatted.error?.message ?? formatted.stderr),
      );
    text(`${options.name}.gen.go`, formatted.stdout);
  } else {
    const module = options.actionsModule;
    if (archive.actions.length && !module)
      throw new Error(
        "JavaScript web programs need --actions-module exporting actions",
      );
    if (
      module &&
      (!module ||
        /[\u0000-\u001f<>\\]/.test(module) ||
        /^[A-Za-z][A-Za-z\d+.-]*:/.test(module) ||
        module.startsWith("//"))
    )
      throw new Error("actions-module requires a local or package import");
    const privateDir = `_${options.name}-javascript`;
    text(
      `${privateDir}/program.js`,
      header + `export default ${archive.code};\n`,
    );
    text(
      `${privateDir}/program.d.ts`,
      header +
        `import type {JavascriptFactory} from "./javascript-types.ts";declare const factory:JavascriptFactory;export default factory;\n`,
    );
    for (const file of ["javascript-view.ts", "javascript-types.ts"])
      text(
        `${privateDir}/${file}`,
        header + (await readFile(new URL(file, import.meta.url), "utf8")),
      );
    text(
      `${privateDir}/${options.name}.tsx`,
      header +
        `import {h,Component,createRef} from "preact";
import {createJavascriptComponent,type JavascriptHandle,type JavascriptProps} from "./javascript-view.ts";
import type {JavascriptArchive,JavascriptActions} from "./javascript-types.ts";
import factory from "./program.js";
const archive=${literal(archive)} as JavascriptArchive;
const Program=createJavascriptComponent(factory,archive);
const emptyActions:JavascriptActions={};
export type ${options.name}Handle=JavascriptHandle;
export class ${options.name} extends Component<JavascriptProps,{loaded?:JavascriptActions;failure?:unknown}> implements JavascriptHandle {
private program=createRef<JavascriptHandle>();private active=false;state:{loaded?:JavascriptActions;failure?:unknown}={};
componentDidMount(){this.active=true;${module ? `if(!this.props.actions)import(${literal(module)}).then(value=>{if(this.active)this.setState({loaded:value.actions});}).catch(error=>{if(this.active)this.setState({failure:error});});` : ""}}
componentWillUnmount(){this.active=false;}
exportJavascript(){if(!this.program.current)throw new Error("Export requires a mounted JavaScript program");return this.program.current.exportJavascript();}
render(){const {loaded,failure}=this.state;if(failure)throw failure;const actions=this.props.actions??loaded${archive.actions.length ? "" : "??emptyActions"};return actions?h(Program,{actions,ref:this.program}):null;}
}
export default ${options.name};\n`,
    );
    text(
      `${options.name}.astro`,
      `---\n${header}import ${options.name} from "./${privateDir}/${options.name}.tsx";\n---\n<${options.name} client:only="preact" />\n`,
      "---\n// Code generated by astro-fyne. DO NOT EDIT.",
    );
  }
  artifacts.push({
    path: join(output, `${options.name}.javascript.report.json`),
    root: output,
    content:
      JSON.stringify(
        {
          schema: 1,
          generator: "astro-fyne",
          kind: "javascript-program",
          name: options.name,
          codeHash: archive.codeHash,
          sources: archive.sources,
          actions: archive.actions,
          runtime: "goja-pure-go",
          nativeWidgets: true,
          state: "program-and-recorded-events",
          visual: { pixelPerfectVerified: false },
          limitations: [
            "native DOM/CSS/control adapters cover documented subset",
            "host actions require finite JSON data; recorded effects are not repeated on restore",
            "delayed timers, network/SSR and arbitrary browser APIs need platform adapters",
            "focus/caret/selection and pending editor text are not portable",
          ],
        },
        null,
        2,
      ) + "\n",
    isOwned: generatedJSON,
  });
  const protectedPaths = [options.source, options.program, options.props]
    .filter((path): path is string => !!path)
    .map((path) => resolve(path));
  if (options.source)
    for (const source of archive.sources)
      protectedPaths.push(
        resolve(dirname(resolve(options.source)), source.path),
      );
  if (
    artifacts.some((artifact) =>
      protectedPaths.includes(resolve(artifact.path)),
    )
  )
    throw new Error("JavaScript output cannot replace source inputs");
  await applyArtifacts(artifacts, { check: options.check ?? false });
  process.stdout.write(
    `${options.check ? "Checked" : "Generated"} ${options.name}: JavaScript → ${options.direction === "native" ? "native Fyne (Goja)" : "Astro + Preact"}.\n`,
  );
  return archive;
}

export async function javascriptMain(
  args: readonly string[],
  direction: "native" | "web",
  check = false,
) {
  const argv = [...args],
    seen = new Set<string>(),
    options: Partial<Options> = { direction, check };
  while (argv.length) {
    const flag = argv.shift()!;
    if (seen.has(flag)) throw usageError(`Duplicate option: ${flag}`);
    seen.add(flag);
    if (flag === "--javascript") continue;
    if (flag === "--check") {
      options.check = true;
      continue;
    }
    if (
      ![
        "--source",
        "--program",
        "--out",
        "--name",
        "--export",
        "--props",
        "--actions",
        "--actions-module",
        "--package",
      ].includes(flag)
    )
      throw usageError(`Unknown JavaScript option: ${flag}`);
    const value = argv.shift();
    if (!value || value.startsWith("-"))
      throw usageError(`Missing value for ${flag}`);
    if (flag === "--source") options.source = value;
    else if (flag === "--program") options.program = value;
    else if (flag === "--out") options.out = value;
    else if (flag === "--name") options.name = value;
    else if (flag === "--export") options.selected = value;
    else if (flag === "--props") options.props = value;
    else if (flag === "--actions") options.actions = value.split(",");
    else if (flag === "--actions-module") options.actionsModule = value;
    else options.packageName = value;
  }
  if (!options.out || !options.name)
    throw usageError("JavaScript mode needs --out and --name");
  if (
    (direction === "native" && options.actionsModule) ||
    (direction === "web" && options.packageName)
  )
    throw usageError(
      "Use --package for native output and --actions-module for web output",
    );
  await generateJavascript(options as Options);
}
