// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Astro Fyne contributors.

import { spawnSync } from "node:child_process";
import { join, resolve } from "node:path";
import {
  applyArtifacts,
  generatedJSON,
  generatedText,
  type Artifact,
} from "./artifacts.ts";
import { readCLIJSON, usageError } from "./cli-help.ts";
import { emitGo, scopeHelper } from "./emit.ts";
import { fontsCSS } from "./fonts.ts";
import { validateProgramArchive } from "./program.ts";
import { emitWebProgram } from "./program-web.ts";

export interface ProgramCLIOptions {
  program: string;
  out: string;
  name: string;
  direction: "web" | "native";
  packageName?: string;
  publicDir?: string;
  actionsModule?: string;
  check?: boolean;
}
export async function generateProgram(options: ProgramCLIOptions) {
  const input = resolve(options.program),
    output = resolve(options.out);
  if (!/^[A-Z][A-Za-z0-9_]*$/.test(options.name))
    throw new Error("Program name must be a capitalized identifier");
  const { archive, program } = validateProgramArchive(
    await readCLIJSON(input, "Program"),
  );
  const artifacts: Artifact[] = [];
  const text = (
    path: string,
    content: string,
    marker = "// Code generated by astro-fyne. DO NOT EDIT.",
  ) =>
    artifacts.push({
      path: join(output, path),
      root: output,
      content,
      isOwned: generatedText(marker),
    });
  let report: unknown;
  if (options.direction === "web") {
    const result = await emitWebProgram(program, archive, {
      name: options.name,
      ...(options.actionsModule
        ? { actionsModule: options.actionsModule }
        : {}),
    });
    for (const [file, content] of Object.entries(result.files))
      text(
        file,
        content,
        file.endsWith(".astro")
          ? "---\n// Code generated by astro-fyne. DO NOT EDIT."
          : file.endsWith(".css")
            ? "/* Code generated by astro-fyne. DO NOT EDIT. */"
            : undefined,
      );
    const publicDir = resolve(options.publicDir ?? join(output, "public"));
    for (const { path, content } of result.assets)
      artifacts.push({
        path: join(publicDir, path),
        root: publicDir,
        content,
        isOwned: (saved) => Buffer.from(saved).equals(Buffer.from(content)),
      });
    report = result.report;
  } else {
    const code = emitGo(program, {
      name: options.name,
      packageName: options.packageName ?? "generated",
      portableProgram: true,
      restoreProgram: JSON.stringify(archive),
    });
    const helper = `// Code generated by astro-fyne. DO NOT EDIT.\n// SPDX-License-Identifier: Apache-2.0\npackage ${options.packageName ?? "generated"}\nimport webui "github.com/thinkddr/astro-fyne/native"\n${scopeHelper}`;
    for (const [file, source] of [
      [`${options.name}.gen.go`, code],
      ["astro_fyne_scope.gen.go", helper],
    ]) {
      const formatted = spawnSync("gofmt", [], {
        input: source,
        encoding: "utf8",
        maxBuffer: 256 * 1024 * 1024,
      });
      if (formatted.error || formatted.status !== 0)
        throw new Error(
          `Cannot format generated program: ${formatted.error?.message ?? formatted.stderr}`,
        );
      text(file!, formatted.stdout);
    }
    if (program.fonts?.length)
      text(
        `${options.name}.fonts.css`,
        "/* Code generated by astro-fyne. DO NOT EDIT. */\n/* SPDX-License-Identifier: Apache-2.0 */\n" +
          fontsCSS(program.fonts),
        "/* Code generated by astro-fyne. DO NOT EDIT. */",
      );
    report = {
      schema: 1,
      generator: "astro-fyne",
      kind: "portable-program",
      name: options.name,
      sourceHash: archive.sourceHash,
      programHash: archive.programHash,
      actions: program.actions,
      visual: { pixelPerfectVerified: false },
    };
  }
  artifacts.push({
    path: join(output, `${options.name}.program.report.json`),
    root: output,
    content: JSON.stringify(report, null, 2) + "\n",
    isOwned: generatedJSON,
  });
  if (artifacts.some((artifact) => resolve(artifact.path) === input))
    throw new Error("Output cannot replace the input program");
  await applyArtifacts(artifacts, { check: options.check ?? false });
  process.stdout.write(
    `${options.check ? "Checked" : "Generated"} ${options.name}: portable program → ${options.direction === "web" ? "Astro + Preact" : "Fyne Go"}; declared state restored.\n`,
  );
}

export async function programMain(
  args: readonly string[],
  direction: "web" | "native",
  check = false,
) {
  const argv = [...args],
    seen = new Set<string>();
  const options: Partial<ProgramCLIOptions> = { direction, check };
  const command = direction === "web" ? "reverse" : "generate";
  while (argv.length) {
    const flag = argv.shift()!;
    if (seen.has(flag)) throw usageError(`Duplicate option: ${flag}`, command);
    seen.add(flag);
    if (flag === "--check") {
      options.check = true;
      continue;
    }
    const flags =
      direction === "web"
        ? ["--program", "--out", "--name", "--public-dir", "--actions-module"]
        : ["--program", "--out", "--name", "--package"];
    if (!flags.includes(flag))
      throw usageError(`Unknown program option: ${flag}`, command);
    const value = argv.shift();
    if (!value || value.startsWith("-"))
      throw usageError(`Missing value for ${flag}.`, command);
    if (flag === "--program") options.program = value;
    else if (flag === "--out") options.out = value;
    else if (flag === "--name") options.name = value;
    else if (flag === "--package") options.packageName = value;
    else if (flag === "--public-dir") options.publicDir = value;
    else options.actionsModule = value;
  }
  const missing = ["program", "out", "name"].filter(
    (key) => !options[key as keyof ProgramCLIOptions],
  );
  if (missing.length)
    throw usageError(
      `Missing required options: ${missing.map((key) => "--" + key).join(", ")}.`,
      command,
    );
  await generateProgram(options as ProgramCLIOptions);
}
