// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Astro Fyne contributors.

import { readFile } from "node:fs/promises";
import type { Program } from "./ir.ts";
import type { ProgramArchive } from "./program.ts";
import { fontsCSS } from "./fonts.ts";

const header =
  "// Code generated by astro-fyne. DO NOT EDIT.\n// SPDX-License-Identifier: Apache-2.0\n";
const literal = (value: unknown) =>
  JSON.stringify(value)
    .replaceAll("<", "\\u003c")
    .replaceAll("\u2028", "\\u2028")
    .replaceAll("\u2029", "\\u2029");

/** Emit a standalone Preact island with its typed, browser-only IR runtime. */
export async function emitWebProgram(
  program: Program,
  archive: ProgramArchive,
  options: { name: string; actionsModule?: string },
) {
  const { name, actionsModule } = options;
  if (!/^[A-Z][A-Za-z0-9_]*$/.test(name))
    throw new Error("Program name must be a capitalized identifier");
  if (
    actionsModule !== undefined &&
    (!actionsModule ||
      /[\u0000-\u001f<>\\]/.test(actionsModule) ||
      /^[A-Za-z][A-Za-z\d+.-]*:/.test(actionsModule) ||
      actionsModule.startsWith("//"))
  )
    throw new Error(
      "actionsModule requires an explicit local or package module import",
    );
  if (program.actions.length && !actionsModule)
    throw new Error(
      "Portable programs with named actions require --actions-module for Astro hydration",
    );
  const assets: { path: string; content: Uint8Array }[] = [];
  const images: Record<string, string> = {};
  for (const resource of program.resources ?? []) {
    const path = `assets/astro-fyne/${resource.hash}.${resource.mediaType === "image/png" ? "png" : "jpg"}`;
    images[resource.name] = "/" + path;
    if (!assets.some((asset) => asset.path === path))
      assets.push({ path, content: Buffer.from(resource.content, "base64") });
  }
  for (const font of program.fonts ?? []) {
    const path = font.webSrc.slice(1);
    if (!assets.some((asset) => asset.path === path))
      assets.push({ path, content: Buffer.from(font.content, "base64") });
  }
  const files: Record<string, string> = {};
  files[`_${name}-program/${name}.tsx`] =
    header +
    `import {h as _afyH} from "preact";
import {forwardRef as _afyForwardRef} from "preact/compat";
import {useEffect as _afyEffect, useState as _afyState} from "preact/hooks";
import {createProgramComponent as _afyCreate, type ProgramHandle, type ProgramProps, type ProgramActions, type PortableArchive as _afyArchiveType} from "./runtime.ts";
import type {Program as _afyProgram} from "./ir.ts";
export type ${name}Handle = ProgramHandle;
export type ${name}Props = ProgramProps;
const _afyArchive = ${literal(archive)} as _afyArchiveType;
const _afyProgram = JSON.parse(_afyArchive.program) as _afyProgram;
const _afyRoot = _afyCreate(_afyProgram, _afyArchive, ${literal(images)});
export const ${name} = _afyForwardRef<${name}Handle, ${name}Props>(function ${name}(input, ref) {
  const [loaded, setLoaded] = _afyState<ProgramActions>();
  const [failure,setFailure] = _afyState<unknown>();
  ${actionsModule ? `_afyEffect(()=>{if(input.actions) return; let active=true; import(${literal(actionsModule)}).then(module=>{if(active) setLoaded(module.actions);}).catch(error=>{if(active) setFailure(error);}); return()=>{active=false;};},[input.actions]);` : ""}
  if(failure) throw failure;
  const actions = input.actions ?? loaded ${program.actions.length ? "" : "?? _afyEmptyActions"};
  return actions ? _afyH(_afyRoot,{...input,actions,ref}) : null;
});
const _afyEmptyActions:ProgramActions = {};
export default ${name};
`;
  files[`${name}.astro`] =
    `---\n${header}import ${name} from "./_${name}-program/${name}.tsx";\nimport "./${name}.fonts.css";\n---\n<${name} client:only="preact" />\n`;
  files[`${name}.fonts.css`] =
    `/* Code generated by astro-fyne. DO NOT EDIT. */\n/* SPDX-License-Identifier: Apache-2.0 */\n${fontsCSS(program.fonts ?? [])}`;
  const helpers = await Promise.all(
    ["program-web-runtime.ts", "program-values.ts", "ir.ts"].map((file) =>
      readFile(new URL(file, import.meta.url), "utf8"),
    ),
  );
  files[`_${name}-program/runtime.ts`] =
    header + helpers[0]!.replaceAll('"./program-values.ts"', '"./values.ts"');
  files[`_${name}-program/values.ts`] = header + helpers[1]!;
  files[`_${name}-program/ir.ts`] = header + helpers[2]!;
  return {
    files,
    assets,
    report: {
      schema: 1,
      generator: "astro-fyne",
      kind: "portable-program",
      name,
      sourceHash: archive.sourceHash,
      programHash: archive.programHash,
      actions: program.actions,
      state: "declared-state-and-list-identities",
      visual: { pixelPerfectVerified: false },
      limitations: [
        "external callbacks need local named actions",
        "CSS source and native theme overrides are outside this archive",
        "focus, caret, selection and pending editor values are not portable state",
      ],
    },
  };
}
