// SPDX-License-Identifier: Apache-2.0
import { isAbsolute, join, relative, resolve, sep } from "node:path";
import { applyArtifacts, generatedJSON, generatedText } from "./artifacts.js";
import { emitWebScene } from "./reverse.js";
import { helpText, readCLIJSON, usageError, wantsHelp } from "./cli-help.js";

export interface ReverseOptions {
  scene: string;
  out: string;
  name: string;
  publicDir?: string;
  actionsModule?: string;
  check?: boolean;
}

export async function generateReverse(options: ReverseOptions): Promise<void> {
  const scenePath = resolve(options.scene);
  const output = resolve(options.out);
  const publicDir = resolve(options.publicDir ?? join(output, "public"));
  const result = emitWebScene(await readCLIJSON(scenePath, "Scene"), {
    name: options.name,
    ...(options.actionsModule ? { actionsModule: options.actionsModule } : {}),
  });
  const destination = (path: string, directory = output): string => {
    if (isAbsolute(path)) throw new Error(`Absolute output path: ${path}`);
    const resolved = resolve(directory, path);
    const rel = relative(directory, resolved);
    if (!rel || rel === ".." || rel.startsWith(`..${sep}`) || isAbsolute(rel))
      throw new Error(`Path escapes the output directory: ${path}`);
    if (resolved === scenePath)
      throw new Error("Output cannot replace the input scene.");
    return resolved;
  };
  await applyArtifacts(
    [
      {
        path: destination(`${options.name}.astro`),
        root: output,
        content: result.astro,
        isOwned: generatedText(
          "---\n// Code generated by astro-fyne. DO NOT EDIT.",
        ),
      },
      {
        path: destination(`${options.name}.tsx`),
        root: output,
        content: result.preact,
        isOwned: generatedText("// Code generated by astro-fyne. DO NOT EDIT."),
      },
      {
        path: destination(`${options.name}.css`),
        root: output,
        content: result.css,
        isOwned: generatedText("/* Code generated by astro-fyne. DO NOT EDIT."),
      },
      {
        path: destination(`${options.name}.reverse.report.json`),
        root: output,
        content: JSON.stringify(result.report, null, 2) + "\n",
        isOwned: generatedJSON,
      },
      ...result.assets.map(({ path, content }) => ({
        path: destination(path, publicDir),
        root: publicDir,
        content,
        // Content-addressed assets are reusable only when the bytes are identical.
        isOwned: (saved: Uint8Array) =>
          Buffer.from(saved).equals(Buffer.from(content)),
      })),
    ],
    { check: options.check ?? false },
  );
  process.stdout.write(
    `${options.check ? "Checked" : "Generated"} ${options.name}: Fyne → Astro + Preact; visual fidelity requires comparing captures.\n`,
  );
}

export async function reverseMain(args: readonly string[]): Promise<void> {
  const argv = [...args];
  if (wantsHelp(argv)) {
    process.stdout.write(helpText("reverse"));
    return;
  }
  const options: Partial<ReverseOptions> = {};
  const seen = new Set<string>();
  while (argv.length) {
    const flag = argv.shift()!;
    if (seen.has(flag))
      throw usageError(`Duplicate option: ${flag}`, "reverse");
    seen.add(flag);
    if (flag === "--check") {
      options.check = true;
      continue;
    }
    if (
      ![
        "--scene",
        "--out",
        "--name",
        "--actions-module",
        "--public-dir",
      ].includes(flag)
    )
      throw usageError(`Unknown option: ${flag}`, "reverse");
    const value = argv.shift();
    if (!value || value.startsWith("-"))
      throw usageError(`Missing value for ${flag}.`, "reverse");
    if (flag === "--scene") options.scene = value;
    else if (flag === "--out") options.out = value;
    else if (flag === "--name") options.name = value;
    else if (flag === "--public-dir") options.publicDir = value;
    else options.actionsModule = value;
  }
  const missing = ["scene", "out", "name"].filter(
    (key) => !options[key as keyof ReverseOptions],
  );
  if (missing.length)
    throw usageError(
      `Missing required options: ${missing.map((key) => `--${key}`).join(", ")}.`,
      "reverse",
    );
  await generateReverse(options as ReverseOptions);
}
