// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Astro Fyne contributors.

import { afterEach, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm, writeFile, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import ts from "typescript";
import { compile } from "./parser.ts";
import {
  emitWebScene,
  validateSceneDocument,
  type SceneDocument,
  type SceneNode,
  type SceneStyle,
} from "./reverse.ts";

const directories: string[] = [];
afterEach(async () => {
  await Promise.all(
    directories
      .splice(0)
      .map((path) => rm(path, { recursive: true, force: true })),
  );
});

function style(overrides: Partial<SceneStyle> = {}): SceneStyle {
  return {
    x: 0,
    y: 0,
    width: 100,
    height: 20,
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    gap: 0,
    direction: "column",
    background: "transparent",
    color: "#11232b",
    borderColor: "#000000",
    borderWidth: 0,
    radius: 0,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: 400,
    fontFamily: "Arial",
    fontStyle: "normal",
    textAlign: "left",
    whiteSpace: "normal",
    display: "block",
    opacity: 1,
    measured: true,
    ...overrides,
  };
}
function node(overrides: Partial<SceneNode> = {}): SceneNode {
  return {
    id: "label",
    kind: "text",
    text:
      !overrides.kind || ["text", "button"].includes(overrides.kind)
        ? "Native"
        : undefined,
    style: style(),
    children: [],
    ...overrides,
  };
}
function document(roots: SceneNode[] = [node()]): SceneDocument {
  return {
    schema: 1,
    viewport: { width: 320, height: 240, scale: 1 },
    roots,
    tokens: { "--color-primary": "#11232b" },
    resources: [],
    requiredActions: [],
  };
}
function syntax(source: string) {
  const parsed = ts.createSourceFile(
    "Generated.tsx",
    source,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TSX,
  ) as ts.SourceFile & { parseDiagnostics: ts.Diagnostic[] };
  expect(parsed.parseDiagnostics).toEqual([]);
}

test("static scenes generate literal Preact that the existing forward compiler can parse", async () => {
  const scene = document([
    node({
      id: "native.root:/",
      kind: "container",
      text: "",
      style: style({ width: 320, height: 240, borderWidth: 2 }),
      children: [
        node({
          id: 'child./:quoted"',
          text: 'A <script> & "quote"',
          style: style({ x: 12, y: 9, width: 80 }),
        }),
      ],
    }),
  ]);
  const generated = emitWebScene(scene, { name: "Scene" });
  syntax(generated.preact);
  expect(generated.preact).not.toMatch(
    /useState|useEffect|useRef|dangerouslySetInnerHTML/,
  );
  expect(generated.preact).toContain("\\u003cscript>");
  expect(generated.css).toContain("left:10px;top:7px");
  expect(generated.css).not.toContain(scene.roots[0]!.id);
  expect(generated.css).toContain("--color-primary:#11232b;");
  expect(generated.report).toMatchObject({
    generator: "astro-fyne",
    direction: "fyne-to-astro",
    visualVerified: false,
    nodeCount: 2,
    rootId: "fyne-root",
  });
  expect(generated.astro).toStartWith(
    "---\n// Code generated by astro-fyne. DO NOT EDIT.\n",
  );
  expect(generated.css).toStartWith(
    "/* Code generated by astro-fyne. DO NOT EDIT.\n",
  );
  const directory = await mkdtemp(join(tmpdir(), "astro-fyne-reverse-"));
  directories.push(directory);
  await writeFile(join(directory, "Scene.tsx"), generated.preact);
  await writeFile(join(directory, "Scene.css"), generated.css);
  const compiled = await compile(join(directory, "Scene.tsx"));
  expect(compiled.hasStyles).toBe(true);
  expect(compiled.actions).toEqual([]);
  expect(compiled.sources.map((source) => source.path)).toEqual([
    "Scene.css",
    "Scene.tsx",
  ]);
});

test("schema validation rejects ambiguous or unsupported scenes before writing artifacts", () => {
  const cases: [unknown, string][] = [
    [{ ...document(), schema: 2 }, "schema"],
    [{ ...document(), unexpected: true }, "unknown field"],
    [document([node(), node()]), "duplicate ID"],
    [document([node({ style: style({ x: NaN }) })]), "finite number"],
    [document([node({ style: style({ width: -1 }) })]), "at least 0"],
    [
      document([node({ style: style({ measured: false }) })]),
      "resolved and measured",
    ],
    [
      document([node({ style: style({ background: "red; color:black" }) })]),
      "solid color",
    ],
    [
      document([node({ style: style({ fontFamily: "Arial;display:none" }) })]),
      "font-family",
    ],
    [
      document([node({ href: "javascript:alert(1)" })]),
      "explicit native action",
    ],
    [
      document([node({ children: [node({ id: "nested" })] })]),
      "only native containers",
    ],
    [document([node({ events: { tap: "click" } })]), "event does not match"],
    [{ ...document(), requiredActions: ["not-used"] }, "match exactly"],
    [
      { ...document(), viewport: { width: 320, height: 240, scale: 3 } },
      "scales",
    ],
    [document([node({ labelFor: "absent" })]), "label target"],
    [
      document([
        node({
          kind: "container",
          text: "overlay",
          children: [node({ id: "child" })],
        }),
      ]),
      "paint-order",
    ],
    [
      document([node({ kind: "input", text: "dropped", value: "visible" })]),
      "overlay text",
    ],
  ];
  for (const [scene, message] of cases)
    expect(() => validateSceneDocument(scene)).toThrow(message);
  const collision = emitWebScene(
    document([node({ id: "fyne-root" }), node({ id: "fyne-root-1" })]),
    { name: "Collision" },
  );
  expect(collision.report.rootId).toBe("fyne-root-2");
  expect(collision.preact).toContain('id={"fyne-root-2"}');
  const scene = document();
  Object.defineProperty(scene, "tokens", {
    get() {
      throw new Error("getter executed");
    },
  });
  expect(() => validateSceneDocument(scene)).toThrow("cannot be accessors");
});

test("DOM text normalization and exact native placeholder colors are explicit boundaries", () => {
  for (const value of ["A\nB", "A\rB"])
    expect(() =>
      validateSceneDocument(document([node({ kind: "input", value })])),
    ).toThrow("cannot preserve CR/LF");
  expect(() =>
    validateSceneDocument(
      document([node({ kind: "textarea", value: "A\r\nB" })]),
    ),
  ).toThrow("CR normalization");
  expect(() =>
    validateSceneDocument(
      document([node({ kind: "input", placeholder: "Name" })]),
    ),
  ).toThrow("exact color");
  const scene = document([
    node({
      kind: "input",
      value: '<unsafe> & "quotes"',
      placeholder: "Name",
      placeholderColor: "rgba(17,35,43,0.55)",
      accessibleLabel: "Name",
    }),
  ]);
  const output = emitWebScene(scene, { name: "Scene" });
  syntax(output.preact);
  expect(output.preact).toContain('initial={"\\u003cunsafe> & \\"quotes\\""}');
  expect(output.css).toContain(
    "::placeholder{color:rgba(17, 35, 43, 0.5490196078431373);opacity:1;font:inherit;line-height:inherit;}",
  );
});

test("native solid colors become valid CSS with the exact resolved RGBA8 channels", () => {
  // Native ParseColor accepts mixed separators, fractional channels and RGB
  // percentages. Passing the spelling through would produce invalid CSS or
  // leave browser rounding to differ from the native 8-bit painter.
  const scene = document([
    node({
      kind: "input",
      placeholder: "Native color",
      placeholderColor: "rgb(100%, 0, 10.4 / 50%)",
      style: style({
        background: "rgba(50%, 0, 25.1 / 50%)",
        color: "rgb(10.4 20.6 30.1 .5)",
        borderColor: " WHITE ",
      }),
    }),
  ]);
  const validated = validateSceneDocument(scene).roots[0]!;
  expect(validated.style.background).toBe(
    "rgba(128, 0, 25, 0.5019607843137255)",
  );
  expect(validated.style.color).toBe("rgba(10, 21, 30, 0.5019607843137255)");
  expect(validated.style.borderColor).toBe("white");
  expect(validated.placeholderColor).toBe(
    "rgba(255, 0, 10, 0.5019607843137255)",
  );
  const generated = emitWebScene(scene, { name: "Scene" });
  expect(generated.css).toContain(
    "background:rgba(128, 0, 25, 0.5019607843137255);",
  );
  expect(generated.css).toContain(
    "::placeholder{color:rgba(255, 0, 10, 0.5019607843137255);",
  );
  expect(generated.css).not.toContain("50%");
  expect(generated.css).not.toContain("10.4");
  expect(scene.roots[0]!.style.background).toBe("rgba(50%, 0, 25.1 / 50%)");
  for (const value of [" ", " Transparent "])
    expect(
      validateSceneDocument(
        document([node({ style: style({ background: value }) })]),
      ).roots[0]!.style.background,
    ).toBe("transparent");
});

test("client actions require a module, exact inventory and no SSR function serialization", () => {
  const scene = document([
    node({ kind: "button", events: { tap: "save:contact" } }),
  ]);
  scene.requiredActions = ["save:contact"];
  expect(() => emitWebScene(scene, { name: "Scene" })).toThrow(
    "explicit client actions module",
  );
  const output = emitWebScene(scene, {
    name: "Scene",
    actionsModule: "./scene-actions.ts",
  });
  expect(output.preact).toContain('import("./scene-actions.ts")');
  expect(output.preact).toContain('boundActions["save:contact"]!()');
  expect(output.astro).not.toContain("actions=");
  expect(output.astro).toContain('client:only="preact"');
  expect(() =>
    emitWebScene(scene, {
      name: "Scene",
      actionsModule: "https://host/action.js",
    }),
  ).toThrow("explicit local");
  expect(() =>
    emitWebScene(scene, { name: "Bad;injected()", actionsModule: "./actions" }),
  ).toThrow("component identifier");
});

test("embedded bitmap bytes, digest, dimensions and output paths reuse shared validation", async () => {
  const bytes = await readFile(
    new URL("../example/public/images/local-image.png", import.meta.url),
  );
  const hash = createHash("sha256").update(bytes).digest("hex");
  const scene = document([
    node({
      kind: "image",
      text: "",
      resource: "picture",
      accessibleLabel: "Local image",
      style: style({ width: 16, height: 16 }),
    }),
  ]);
  scene.resources = [
    {
      name: "picture",
      path: `assets/${hash}.png`,
      hash,
      mediaType: "image/png",
      content: bytes.toString("base64"),
      width: 16,
      height: 16,
    },
  ];
  const output = emitWebScene(scene, { name: "Scene" });
  expect(output.assets[0]!.content).toEqual(bytes);
  expect(output.preact).toContain(`src={"/assets/${hash}.png"}`);
  expect(output.preact).toContain('alt={"Local image"}');
  const noPixels = Buffer.concat([
    bytes.subarray(0, 33),
    bytes.subarray(bytes.length - 12),
  ]);
  const noPixelsHash = createHash("sha256").update(noPixels).digest("hex");
  expect(() =>
    emitWebScene(
      {
        ...scene,
        resources: [
          {
            ...scene.resources[0]!,
            hash: noPixelsHash,
            content: noPixels.toString("base64"),
          },
        ],
      },
      { name: "Scene" },
    ),
  ).toThrow("has no IDAT data");
  for (const resource of [
    { ...scene.resources[0]!, hash: "0".repeat(64) },
    { ...scene.resources[0]!, path: "../escape.png" },
    { ...scene.resources[0]!, width: 17 },
    { ...scene.resources[0]!, mediaType: "image/svg+xml" },
    { ...scene.resources[0]!, content: bytes.toString("base64") + "\n" },
  ])
    expect(() =>
      validateSceneDocument({ ...scene, resources: [resource] }),
    ).toThrow();
  expect(() => validateSceneDocument({ ...scene, resources: [] })).toThrow(
    "bitmap resource is missing",
  );
  const directory = await mkdtemp(join(tmpdir(), "astro-fyne-reverse-image-"));
  directories.push(directory);
  await mkdir(join(directory, "public", "assets"), { recursive: true });
  await writeFile(
    join(directory, "public", output.assets[0]!.path),
    output.assets[0]!.content,
  );
  await writeFile(join(directory, "Scene.tsx"), output.preact);
  await writeFile(join(directory, "Scene.css"), output.css);
  const compiled = await compile(join(directory, "Scene.tsx"), undefined, {
    publicDir: join(directory, "public"),
  });
  expect(compiled.resources?.[0]!.hash).toBe(hash);
});

interface VNode {
  type: unknown;
  props: Record<string, unknown>;
  children: unknown[];
}
function executeGenerated(source: string) {
  // Execute only our generated template in a minimal hook/JSX harness. Scene data
  // stays literal; this verifies emitted callbacks, not a copy of their algorithm.
  const js = ts.transpileModule(source, {
    compilerOptions: {
      target: ts.ScriptTarget.ESNext,
      module: ts.ModuleKind.ESNext,
      jsx: ts.JsxEmit.React,
      jsxFactory: "h",
    },
  }).outputText;
  const ast = ts.createSourceFile(
    "Scene.js",
    js,
    ts.ScriptTarget.ESNext,
    true,
    ts.ScriptKind.JS,
  );
  const statements = ast.statements.filter(
    (statement) =>
      !ts.isImportDeclaration(statement) && !ts.isExportAssignment(statement),
  );
  const printer = ts.createPrinter();
  const body = statements
    .map((statement) => {
      const stripped = ts.isFunctionDeclaration(statement)
        ? ts.factory.updateFunctionDeclaration(
            statement,
            statement.modifiers?.filter(
              (modifier) => modifier.kind !== ts.SyntaxKind.ExportKeyword,
            ),
            statement.asteriskToken,
            statement.name,
            statement.typeParameters,
            statement.parameters,
            statement.type,
            statement.body,
          )
        : statement;
      return printer.printNode(ts.EmitHint.Unspecified, stripped, ast);
    })
    .join("\n");
  const states: unknown[] = [];
  const load = new Function(
    "h",
    "useState",
    "useRef",
    "useEffect",
    `${body}\nreturn {Scene,requireSceneActions};`,
  );
  return load(
    (
      type: unknown,
      props: Record<string, unknown>,
      ...children: unknown[]
    ) => ({ type, props, children }),
    (initial: unknown) => [initial, (value: unknown) => states.push(value)],
    (current: unknown) => ({ current }),
    () => {},
  ) as {
    Scene: (props: { actions: Record<string, unknown> }) => VNode;
    requireSceneActions: (actions: Record<string, unknown>) => void;
  };
}

test("emitted input callbacks preserve immediate input, focus commit, Enter submit and deduplication", () => {
  const field = node({
    kind: "input",
    text: "",
    value: "initial",
    events: { input: "input", change: "change", submit: "submit" },
  });
  const scene = document([field]);
  scene.requiredActions = ["change", "input", "submit"];
  const output = emitWebScene(scene, {
    name: "Scene",
    actionsModule: "./actions",
  });
  syntax(output.preact);
  const compiled = executeGenerated(output.preact);
  const events: string[] = [];
  const actions = {
    input: (value: string) => events.push(`input:${value}`),
    change: (value: string) => events.push(`change:${value}`),
    submit: (value: string) => events.push(`submit:${value}`),
  };
  expect(() => compiled.requireSceneActions({ input() {} })).toThrow(
    "Missing native scene action",
  );
  expect(() => compiled.requireSceneActions(Object.create(actions))).toThrow(
    "Missing native scene action",
  );
  const fieldNode = compiled.Scene({ actions }).children[0] as VNode;
  const input = (fieldNode.type as (props: Record<string, unknown>) => VNode)(
    fieldNode.props,
  );
  expect(input.type).toBe("input");
  const handlers = input.props as Record<string, (event: unknown) => void>;
  handlers.onFocus!({ currentTarget: { value: "initial" } });
  handlers.onInput!({ currentTarget: { value: "changed" } });
  handlers.onInput!({ currentTarget: { value: "changed" } });
  handlers.onKeyDown!({
    currentTarget: { value: "changed" },
    key: "Enter",
    isComposing: false,
    preventDefault() {},
  });
  handlers.onBlur!({ currentTarget: { value: "changed" } });
  expect(events).toEqual(["input:changed", "change:changed", "submit:changed"]);
  handlers.onFocus!({ currentTarget: { value: "changed" } });
  handlers.onInput!({ currentTarget: { value: "other" } });
  handlers.onInput!({ currentTarget: { value: "changed" } });
  handlers.onBlur!({ currentTarget: { value: "changed" } });
  expect(events.slice(3)).toEqual(["input:other", "input:changed"]);
  const length = events.length;
  handlers.onKeyDown!({
    currentTarget: { value: "changed" },
    key: "Enter",
    isComposing: true,
    preventDefault() {
      throw new Error("IME interrupted");
    },
  });
  expect(events).toHaveLength(length);
});

test("emitted textarea Enter and disabled controls do not infer submit behavior", () => {
  const input = node({
    kind: "textarea",
    text: "",
    value: "A\nB",
    events: { change: "change" },
  });
  const scene = document([input]);
  scene.requiredActions = ["change"];
  const compiled = executeGenerated(
    emitWebScene(scene, { name: "Scene", actionsModule: "./actions" }).preact,
  );
  const observed: string[] = [];
  const actions = { change: (value: string) => observed.push(value) };
  const fieldNode = compiled.Scene({ actions }).children[0] as VNode;
  const textarea = (
    fieldNode.type as (props: Record<string, unknown>) => VNode
  )(fieldNode.props);
  expect(textarea.type).toBe("textarea");
  const handlers = textarea.props as Record<string, (event: unknown) => void>;
  handlers.onInput!({ currentTarget: { value: "changed\nline" } });
  handlers.onKeyDown!({
    currentTarget: { value: "changed\nline" },
    key: "Enter",
    preventDefault() {
      throw new Error("newline prevented");
    },
  });
  expect(observed).toEqual([]);
  handlers.onBlur!({ currentTarget: { value: "changed\nline" } });
  expect(observed).toEqual(["changed\nline"]);
  const disabled = (
    fieldNode.type as (props: Record<string, unknown>) => VNode
  )({ ...fieldNode.props, disabled: true });
  const disabledHandlers = disabled.props as Record<
    string,
    (event: unknown) => void
  >;
  disabledHandlers.onInput!({ currentTarget: { value: "blocked" } });
  disabledHandlers.onBlur!({ currentTarget: { value: "blocked" } });
  expect(observed).toEqual(["changed\nline"]);
  expect(() =>
    validateSceneDocument({
      ...scene,
      roots: [{ ...input, events: { submit: "change" } }],
    }),
  ).toThrow("multiline submit");
});
