// SPDX-License-Identifier: Apache-2.0
import { readFile } from "node:fs/promises";
import { isAbsolute, join, relative, resolve, sep } from "node:path";
import { applyArtifacts, generatedJSON, generatedText } from "./artifacts.js";
import { emitWebScene } from "./reverse.js";

export interface ReverseOptions {
  scene: string;
  out: string;
  name: string;
  publicDir?: string;
  actionsModule?: string;
  check?: boolean;
}

export async function generateReverse(options: ReverseOptions): Promise<void> {
  const scenePath = resolve(options.scene);
  const output = resolve(options.out);
  const publicDir = resolve(options.publicDir ?? join(output, "public"));
  const result = emitWebScene(JSON.parse(await readFile(scenePath, "utf8")), {
    name: options.name,
    ...(options.actionsModule ? { actionsModule: options.actionsModule } : {}),
  });
  const destination = (path: string, directory = output): string => {
    if (isAbsolute(path)) throw new Error(`Ruta de salida absoluta: ${path}`);
    const resolved = resolve(directory, path);
    const rel = relative(directory, resolved);
    if (!rel || rel === ".." || rel.startsWith(`..${sep}`) || isAbsolute(rel))
      throw new Error(`Ruta fuera del directorio de salida: ${path}`);
    if (resolved === scenePath)
      throw new Error("La salida no puede reemplazar la escena de entrada.");
    return resolved;
  };
  await applyArtifacts(
    [
      {
        path: destination(`${options.name}.astro`),
        root: output,
        content: result.astro,
        isOwned: generatedText(
          "---\n// Code generated by astro-fyne. DO NOT EDIT.",
        ),
      },
      {
        path: destination(`${options.name}.tsx`),
        root: output,
        content: result.preact,
        isOwned: generatedText("// Code generated by astro-fyne. DO NOT EDIT."),
      },
      {
        path: destination(`${options.name}.css`),
        root: output,
        content: result.css,
        isOwned: generatedText("/* Code generated by astro-fyne. DO NOT EDIT."),
      },
      {
        path: destination(`${options.name}.reverse.report.json`),
        root: output,
        content: JSON.stringify(result.report, null, 2) + "\n",
        isOwned: generatedJSON,
      },
      ...result.assets.map(({ path, content }) => ({
        path: destination(path, publicDir),
        root: publicDir,
        content,
        // Content-addressed assets are reusable only when the bytes are identical.
        isOwned: (saved: Uint8Array) =>
          Buffer.from(saved).equals(Buffer.from(content)),
      })),
    ],
    { check: options.check ?? false },
  );
  process.stdout.write(
    `${options.check ? "Comprobada" : "Generada"} ${options.name}: Fyne → Astro + Preact; fidelidad visual requiere comparación de capturas.\n`,
  );
}

export async function reverseMain(argv: string[]): Promise<void> {
  const options: Partial<ReverseOptions> = {};
  const seen = new Set<string>();
  while (argv.length) {
    const flag = argv.shift()!;
    if (seen.has(flag)) throw new Error(`Opción duplicada: ${flag}`);
    seen.add(flag);
    if (flag === "--check") {
      options.check = true;
      continue;
    }
    if (
      ![
        "--scene",
        "--out",
        "--name",
        "--actions-module",
        "--public-dir",
      ].includes(flag)
    )
      throw new Error(`Opción desconocida: ${flag}`);
    const value = argv.shift();
    if (!value || value.startsWith("--"))
      throw new Error(`Falta valor de ${flag}`);
    if (flag === "--scene") options.scene = value;
    else if (flag === "--out") options.out = value;
    else if (flag === "--name") options.name = value;
    else if (flag === "--public-dir") options.publicDir = value;
    else options.actionsModule = value;
  }
  if (!options.scene || !options.out || !options.name)
    throw new Error(
      "Uso: astro-fyne reverse --scene escena.json --out directorio --name Nombre [--public-dir Astro/public] [--actions-module ./actions] [--check]",
    );
  await generateReverse(options as ReverseOptions);
}
