// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Astro Fyne contributors.

import { spawnSync } from "node:child_process";
import { dirname, join, resolve } from "node:path";
import { applyArtifacts, generatedJSON, generatedText } from "./artifacts.ts";
import { fontsCSS, loadFonts } from "./fonts.ts";
import type { FontFace } from "./ir.ts";
import { readCLIJSON, usageError } from "./cli-help.ts";
import { emitNativeScene } from "./scene-native.ts";

export interface NativeSceneCLIOptions {
  scene: string;
  out: string;
  name: string;
  packageName?: string;
  fonts?: string;
  check?: boolean;
}
export async function generateNativeScene(
  options: NativeSceneCLIOptions,
): Promise<void> {
  const scenePath = resolve(options.scene);
  const output = resolve(options.out);
  const fontConfig = options.fonts ? resolve(options.fonts) : undefined;
  const fonts = fontConfig
    ? await loadFonts(
        (await readCLIJSON(fontConfig, "Fonts")) as FontFace[],
        dirname(fontConfig),
      )
    : [];
  const result = emitNativeScene(await readCLIJSON(scenePath, "Scene"), {
    name: options.name,
    packageName: options.packageName ?? "generated",
    fonts,
  });
  const formatted = spawnSync("gofmt", [], {
    input: result.code,
    encoding: "utf8",
    maxBuffer: 256 * 1024 * 1024,
  });
  if (formatted.error)
    throw new Error(`Cannot run gofmt: ${formatted.error.message}`);
  if (formatted.status !== 0)
    throw new Error(`Invalid generated native scene: ${formatted.stderr}`);
  const artifacts = [
    {
      path: join(output, `${options.name}.gen.go`),
      root: output,
      content: formatted.stdout,
      isOwned: generatedText("// Code generated by astro-fyne. DO NOT EDIT."),
    },
    {
      path: join(output, `${options.name}.gen.report.json`),
      root: output,
      content: JSON.stringify(result.report, null, 2) + "\n",
      isOwned: generatedJSON,
    },
    ...(fonts.length
      ? [
          {
            path: join(output, `${options.name}.gen.fonts.css`),
            root: output,
            content:
              "/* Code generated by astro-fyne. DO NOT EDIT. */\n/* SPDX-License-Identifier: Apache-2.0 */\n" +
              fontsCSS(fonts),
            isOwned: generatedText(
              "/* Code generated by astro-fyne. DO NOT EDIT. */",
            ),
          },
        ]
      : []),
  ];
  if (
    artifacts.some(
      (artifact) => artifact.path === scenePath || artifact.path === fontConfig,
    )
  )
    throw new Error(
      "Output cannot replace the input scene or fonts configuration",
    );
  await applyArtifacts(artifacts, { check: options.check ?? false });
  process.stdout.write(
    `${options.check ? "Checked" : "Generated"} ${options.name}: scene → Fyne (${result.report.layout}); visual fidelity requires comparing captures.\n`,
  );
}

export async function nativeSceneMain(
  args: readonly string[],
  check = false,
): Promise<void> {
  const argv = [...args];
  const options: Partial<NativeSceneCLIOptions> = { check };
  const seen = new Set<string>();
  while (argv.length) {
    const flag = argv.shift()!;
    if (seen.has(flag))
      throw usageError(`Duplicate option: ${flag}`, "generate");
    seen.add(flag);
    if (flag === "--check") {
      options.check = true;
      continue;
    }
    if (!["--scene", "--out", "--name", "--package", "--fonts"].includes(flag))
      throw usageError(`Unknown scene option: ${flag}`, "generate");
    const value = argv.shift();
    if (!value || value.startsWith("-"))
      throw usageError(`Missing value for ${flag}.`, "generate");
    if (flag === "--scene") options.scene = value;
    else if (flag === "--out") options.out = value;
    else if (flag === "--name") options.name = value;
    else if (flag === "--package") options.packageName = value;
    else options.fonts = value;
  }
  const missing = ["scene", "out", "name"].filter(
    (key) => !options[key as keyof NativeSceneCLIOptions],
  );
  if (missing.length)
    throw usageError(
      `Missing required options: ${missing.map((key) => `--${key}`).join(", ")}.`,
      "generate",
    );
  await generateNativeScene(options as NativeSceneCLIOptions);
}
